name: Release StudentDesk

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Prepare cache dirs
        run: |
          mkdir -p ~/.cache/electron ~/.cache/electron-builder

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/electron
            ~/.cache/electron-builder
            node_modules
          key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-

      - name: Install deps
        run: npm ci

      - name: Build & publish (x64+arm64 en 1 run)
        run: npm run release:both
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
